language: node_js
node_js: '11'
dist: trusty
cache: npm

install:
  - make node_modules

script:
  - make build

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        git remote add gitlab https://oauth2:"$TOKEN"@gitlab.com/cgm616/cgm616.me.git
        git push gitlab master
      fi
