# Settings
baseURL = "https://cgm616.me/"
languageCode = "en-US"                  # or en-US
title = "CGM"
description = "Cole's personal website"
theme = ["basic"]
canonifyURLs = true
copyright = "Cole Graber-Mitchell"
enableRobotsTXT = true
enableGitInfo = true
pygmentsUseClasses = true

[markup]
defaultMarkdownHandler = "pandoc"

[markup.pandoc.renderer]
unsafe = true

[security.exec]
allow = ["pandoc", "bin/pandoc"]

[minify]
minifyOutput = true

[sitemap]
changefreq = "weekly"
priority = 0.5

[permalinks]
posts = "/:year/:month/:slug/"
page = "/:slug/"

[taxonomies]
tag = 'tags'

[menu]
[[menu.main]]
name = 'Home'
pageRef = '/'
url = '/'
weight = 10
[[menu.main]]
name = 'Writing'
url = '/writing/'
pageRef = '/writing'
weight = 20
[[menu.main]]
name = 'Research'
url = '/research/'
pageRef = '/research'
weight = 30
[[menu.main]]
name = 'Resumé'
url = '/resume/'
pageRef = '/resume'
weight = 40
[[menu.main]]
name = 'About'
url = '/about/'
pageRef = '/about'
weight = 50
[[menu.main]]
name = 'Contact'
url = '/contact'
pageRef = '/contact'
weight = 60
[[menu.index]]
pageRef = "/about"
weight = 10
name = "About me"
[menu.index.params]
text = "I live in London, but I'm from Minneapolis. Some of my passions are the outdoors, good books, singing, and printmaking."
more = "Learn more"
sideImg = ""
[[menu.index]]
pageRef = "/writing"
weight = 20
name = "My writing"
[menu.index.params]
text = "I find that writing helps me think. It's also good to practice. Here, I write about anything I'm thinking about."
more = "Read more"
[[menu.index]]
pageRef = "/research"
weight = 30
name = "My research"
[menu.index.params]
text = "I do interdisciplinary research on law and politics in social context. Among other topics, I have investigated religion in the legal process and lethal injection."
more = "Cite more"
side = "/gallery/lethal_injection_book/cover.jpg"
[[menu.index]]
pageRef = "/resume"
url = "/resume/"
weight = 25
name = "My resume"
[menu.index.params]
text = "I've worked as a researcher, a campaigner, a teaching assistant, and more. My resume has the full details, including my education."
more = "See more"
[[menu.index]]
pageRef = "/links"
url = "/links/"
weight = 25
name = "Links"
[menu.index.params]
text = "Here are links to cool sites I've found around the web with my commentary. It's a cross between my broswer bookmarks and an annotated bibliography."
more = "Browse more"
